# coding: utf-8

"""
    SensorPush Public API

    This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).  # noqa: E501

    OpenAPI spec version: v1.0.20240629
    Contact: support@sensorpush.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReportListing(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'last_modified': 'datetime',
        'name': 'str',
        'size': 'str'
    }

    attribute_map = {
        'last_modified': 'last_modified',
        'name': 'name',
        'size': 'size'
    }

    def __init__(self, last_modified=None, name=None, size=None):  # noqa: E501
        """ReportListing - a model defined in Swagger"""  # noqa: E501
        self._last_modified = None
        self._name = None
        self._size = None
        self.discriminator = None
        if last_modified is not None:
            self.last_modified = last_modified
        if name is not None:
            self.name = name
        if size is not None:
            self.size = size

    @property
    def last_modified(self):
        """Gets the last_modified of this ReportListing.  # noqa: E501

        Date file was last modified  # noqa: E501

        :return: The last_modified of this ReportListing.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified):
        """Sets the last_modified of this ReportListing.

        Date file was last modified  # noqa: E501

        :param last_modified: The last_modified of this ReportListing.  # noqa: E501
        :type: datetime
        """

        self._last_modified = last_modified

    @property
    def name(self):
        """Gets the name of this ReportListing.  # noqa: E501

        Name of the file  # noqa: E501

        :return: The name of this ReportListing.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ReportListing.

        Name of the file  # noqa: E501

        :param name: The name of this ReportListing.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def size(self):
        """Gets the size of this ReportListing.  # noqa: E501

        File size  # noqa: E501

        :return: The size of this ReportListing.  # noqa: E501
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this ReportListing.

        File size  # noqa: E501

        :param size: The size of this ReportListing.  # noqa: E501
        :type: str
        """

        self._size = size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReportListing, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportListing):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
