# coding: utf-8

"""
    SensorPush Public API

    This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).  # noqa: E501

    OpenAPI spec version: v1.0.20240629
    Contact: support@sensorpush.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SensorAlerts(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'humidity': 'SensorAlertsHumidity',
        'temperature': 'SensorAlertsTemperature'
    }

    attribute_map = {
        'humidity': 'humidity',
        'temperature': 'temperature'
    }

    def __init__(self, humidity=None, temperature=None):  # noqa: E501
        """SensorAlerts - a model defined in Swagger"""  # noqa: E501
        self._humidity = None
        self._temperature = None
        self.discriminator = None
        if humidity is not None:
            self.humidity = humidity
        if temperature is not None:
            self.temperature = temperature

    @property
    def humidity(self):
        """Gets the humidity of this SensorAlerts.  # noqa: E501


        :return: The humidity of this SensorAlerts.  # noqa: E501
        :rtype: SensorAlertsHumidity
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity):
        """Sets the humidity of this SensorAlerts.


        :param humidity: The humidity of this SensorAlerts.  # noqa: E501
        :type: SensorAlertsHumidity
        """

        self._humidity = humidity

    @property
    def temperature(self):
        """Gets the temperature of this SensorAlerts.  # noqa: E501


        :return: The temperature of this SensorAlerts.  # noqa: E501
        :rtype: SensorAlertsTemperature
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this SensorAlerts.


        :param temperature: The temperature of this SensorAlerts.  # noqa: E501
        :type: SensorAlertsTemperature
        """

        self._temperature = temperature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SensorAlerts, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SensorAlerts):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
