# coding: utf-8

"""
    SensorPush Public API

    This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).  # noqa: E501

    OpenAPI spec version: v1.0.20240629
    Contact: support@sensorpush.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SensorAlertsHumidity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'max': 'float',
        'min': 'float'
    }

    attribute_map = {
        'enabled': 'enabled',
        'max': 'max',
        'min': 'min'
    }

    def __init__(self, enabled=None, max=None, min=None):  # noqa: E501
        """SensorAlertsHumidity - a model defined in Swagger"""  # noqa: E501
        self._enabled = None
        self._max = None
        self._min = None
        self.discriminator = None
        if enabled is not None:
            self.enabled = enabled
        if max is not None:
            self.max = max
        if min is not None:
            self.min = min

    @property
    def enabled(self):
        """Gets the enabled of this SensorAlertsHumidity.  # noqa: E501

        Is enabled?  # noqa: E501

        :return: The enabled of this SensorAlertsHumidity.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this SensorAlertsHumidity.

        Is enabled?  # noqa: E501

        :param enabled: The enabled of this SensorAlertsHumidity.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def max(self):
        """Gets the max of this SensorAlertsHumidity.  # noqa: E501

        Max threshold for alert  # noqa: E501

        :return: The max of this SensorAlertsHumidity.  # noqa: E501
        :rtype: float
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this SensorAlertsHumidity.

        Max threshold for alert  # noqa: E501

        :param max: The max of this SensorAlertsHumidity.  # noqa: E501
        :type: float
        """

        self._max = max

    @property
    def min(self):
        """Gets the min of this SensorAlertsHumidity.  # noqa: E501

        Min threshold for alert  # noqa: E501

        :return: The min of this SensorAlertsHumidity.  # noqa: E501
        :rtype: float
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this SensorAlertsHumidity.

        Min threshold for alert  # noqa: E501

        :param min: The min of this SensorAlertsHumidity.  # noqa: E501
        :type: float
        """

        self._min = min

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SensorAlertsHumidity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SensorAlertsHumidity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
