# coding: utf-8

"""
    SensorPush Public API

    This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).

    The version of the OpenAPI document: v1.0.20240803
    Contact: support@sensorpush.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional

try:
    from pydantic.v1 import BaseModel, Field, StrictInt, StrictStr
except ImportError:
    from pydantic import BaseModel, Field, StrictInt, StrictStr

class Status(BaseModel):
    """
    Status
    """
    deployed: Optional[StrictStr] = Field(default=None, description="Date time when this service was last updated.")
    message: StrictStr = Field(default=..., description="Greeting message.")
    ms: Optional[StrictInt] = Field(default=None, description="Current date time on the server in milliseconds.")
    stack: Optional[StrictStr] = Field(default=None, description="Active stack hosting this service.")
    status: Optional[StrictStr] = Field(default=None, description="Current status of the api service.")
    time: Optional[StrictStr] = Field(default=None, description="Current date time on the server.")
    version: Optional[StrictStr] = Field(default=None, description="Version of this service currently deployed")
    __properties = ["deployed", "message", "ms", "stack", "status", "time", "version"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Status:
        """Create an instance of Status from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Status:
        """Create an instance of Status from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Status.parse_obj(obj)

        _obj = Status.parse_obj({
            "deployed": obj.get("deployed"),
            "message": obj.get("message"),
            "ms": obj.get("ms"),
            "stack": obj.get("stack"),
            "status": obj.get("status"),
            "time": obj.get("time"),
            "version": obj.get("version")
        })
        return _obj


