# coding: utf-8

"""
    SensorPush Public API

    This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).

    The version of the OpenAPI document: v1.0.20240803
    Contact: support@sensorpush.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensorpush_api.api.api_api import ApiApi  # noqa: E501


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self) -> None:
        pass

    def tearDown(self) -> None:
        pass

    def test_access_token(self) -> None:
        """Test case for access_token

        Request a temporary oAuth access code.  # noqa: E501
        """
        pass

    def test_download(self) -> None:
        """Test case for download

        Download bulk reports.  # noqa: E501
        """
        pass

    def test_gateways(self) -> None:
        """Test case for gateways

        Lists all gateways.  # noqa: E501
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        Lists reports available for download.  # noqa: E501
        """
        pass

    def test_oauth_authorize_post(self) -> None:
        """Test case for oauth_authorize_post

        Sign in and request an authorization code  # noqa: E501
        """
        pass

    def test_root_post(self) -> None:
        """Test case for root_post

        SensorPush API status  # noqa: E501
        """
        pass

    def test_samples(self) -> None:
        """Test case for samples

        Queries for sensor samples.  # noqa: E501
        """
        pass

    def test_sensors(self) -> None:
        """Test case for sensors

        Lists all sensors.  # noqa: E501
        """
        pass

    def test_tags_response(self) -> None:
        """Test case for tags_response

        Updates tags on devices.  # noqa: E501
        """
        pass

    def test_token(self) -> None:
        """Test case for token

        oAuth 2.0 for authorization, access, and refresh tokens  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
