# coding: utf-8

"""
    SensorPush Public API

    This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).

    The version of the OpenAPI document: v1.0.20240803
    Contact: support@sensorpush.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sensorpush_api.models.sensor_alerts_humidity import SensorAlertsHumidity  # noqa: E501

class TestSensorAlertsHumidity(unittest.TestCase):
    """SensorAlertsHumidity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SensorAlertsHumidity:
        """Test SensorAlertsHumidity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SensorAlertsHumidity`
        """
        model = SensorAlertsHumidity()  # noqa: E501
        if include_optional:
            return SensorAlertsHumidity(
                enabled = True,
                max = 1.337,
                min = 1.337
            )
        else:
            return SensorAlertsHumidity(
        )
        """

    def testSensorAlertsHumidity(self):
        """Test SensorAlertsHumidity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
