# coding: utf-8

"""
    SensorPush Public API

    This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).  # noqa: E501

    OpenAPI spec version: v1.0.20240629
    Contact: support@sensorpush.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sensorpush_api
from sensorpush_api.models.token_response import TokenResponse  # noqa: E501
from sensorpush_api.rest import ApiException


class TestTokenResponse(unittest.TestCase):
    """TokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenResponse(self):
        """Test TokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sensorpush_api.models.token_response.TokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
