# coding: utf-8

"""
    SensorPush Public API

    This is a swagger definition for the SensorPush public REST API. Download the definition file [here](https://api.sensorpush.com/api/v1/support/swagger/swagger-v1.json).

    The version of the OpenAPI document: v1.0.20240803
    Contact: support@sensorpush.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from sensorpush_api.models.tags_request import TagsRequest  # noqa: E501

class TestTagsRequest(unittest.TestCase):
    """TagsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagsRequest:
        """Test TagsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagsRequest`
        """
        model = TagsRequest()  # noqa: E501
        if include_optional:
            return TagsRequest(
                sensors = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return TagsRequest(
        )
        """

    def testTagsRequest(self):
        """Test TagsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
