name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install -e .[test]
      - name: Run tests
        # swagger-codegen generates tests that rely on nose, however it is
        # unmaintained and no longer works with Python 3.9 and up;
        # see: https://github.com/nose-devs/nose/issues/1099
        #run: nosetests
        run: python setup.py test
